name: NLP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # - scipy
  # - numpy
  # - pandas
  # - matplotlib
  # - pyyaml
  # - openpyxl
  # - scikit-learn
  # - statsmodels
  # - decorator
  # - tqdm
  # - plotly
  # - nbformat
  # - seaborn
  - pip
  - pip:
    - tensorflow
